### ISSUE TITLE
Template Rendering is failing?

### ISSUE THREAD

**Issue by rkarumanchi** [im7mortal/gowall#1]
I'm facing issue when browsing through pages with <% and %> tags included. Template rendering is failing. Can you please share more detailed setup steps ? (How to do Asset pipeline with grunt and building front end)
 

....
[GIN-debug] PUT    /account/settings/identity/ --> main.changeIdentity (9 handlers)
[GIN-debug] PUT    /account/settings/password/ --> main.changePassword (9 handlers)
[GIN-debug] GET    /account/providerSettings/:provider/ --> main.settingsProvider_ (9 handlers)
[GIN-debug] GET    /account/providerSettings/:provider/disconnect/ --> main.disconnectProvider (9 handlers)
[GIN-debug] Listening and serving HTTP on :3000
                                                                         [GIN] 2017/04/26 - 17:44:31 |[97;42m 200 [0m|      1.9995ms | ::1 |[97;44m  [0m GET     /
[GIN] 2017/04/26 - 17:44:34 |[97;42m 200 [0m|      2.0009ms | ::1 |[97;44m  [0m GET     /about/
html/template:default.html: "\"" in attribute name: "has-error\" : \"\" %>\">\n\t\t<label>Yo"
 [GIN] 2017/04/26 - 17:44:38 |[97;42m 200 [0m|       999.7µs | ::1 |[97;44m  [0m GET     /contact/
html/template:default.html: "\"" in attribute name: "has-error\" : \"\" %>\">\n\t\t<label>Us"
 [GIN] 2017/04/26 - 17:47:22 |[97;42m 200 [0m|      1.0026ms | ::1 |[97;44m  [0m GET     /login/
[GIN] 2017/04/26 - 17:47:25 |[97;42m 200 [0m|            0s | ::1 |[97;44m  [0m GET     /
html/template:default.html: "\"" in attribute name: "has-error\" : \"\" %>\">\n\t\t<label>Pi"
 [GIN] 2017/04/26 - 17:47:30 |[97;42m 200 [0m|      2.0069ms | ::1 |[97;44m  [0m GET     /signup/

I have my setup with Go+mongodb on win10.

**Comment by im7mortal** [comment]
@rkarumanchi 
Sorry for delay. Why you think ``` <% and %> ``` should be supported?
Anyway  sorry for misunderstanding. I have to close this project. **[NodeJS version](https://github.com/jedireza/drywall/)** was abandoned. Now author start promote [new project.](https://github.com/jedireza/aqua/) Without independent supporting of client of _drywall_ this project doesn't sense. 
Sorry. 
I will shut project.
